# Generated by Django 5.0.6 on 2024-07-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_razor_pay_order_id_order_razor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razor_pay_order_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='razor_pay_payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='razor_pay_payment_signature',
            new_name='razorpay_payment_signature',
        ),
    ]
