# Generated by Django 5.0.6 on 2024-07-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_razor_pay_order_id_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_payment_signature',
            new_name='razor_pay_payment_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_order_id',
            new_name='razor_pay_payment_signature',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='order',
            name='razor_pay_order_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
